services:
  - "postgres:12.3"

variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: anwesende
  POSTGRES_USER: anwesende
  POSTGRES_PASSWORD: anwesende

stages:
  - test

pytest:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - mypy anwesende
    - pytest
